import {images} from '../themes';
export default ConstantUtils = {
  BannerData: [
    'https://riz.shop/wp-content/uploads/mobilebanner1.jpg',
    'https://riz.shop/wp-content/uploads/mobilebanner2.jpg',
    'https://riz.shop/wp-content/uploads/mobilebanner3.jpg',
  ],
  arrayState: [
    {label: 'Alexandria', value: 'Alexandria', stateCode: 'EGALX'},
    {label: 'Aswan', value: 'Aswan', stateCode: 'EGASN'},
    {label: 'Asyut', value: 'Asyut', stateCode: 'EGAST'},
    {label: 'Red Sea', value: 'Red Sea', stateCode: 'EGBA'},
    {label: 'Beheira', value: 'Beheira', stateCode: 'EGBH'},
    {label: 'Beni Suef', value: 'Beni Suef', stateCode: 'EGBNS'},
    {label: 'Cairo', value: 'Cairo', stateCode: 'EGC'},
    {label: 'Dakahlia', value: 'Dakahlia', stateCode: 'EGDK'},
    {label: 'Damietta', value: 'Damietta', stateCode: 'EGDT'},
    {label: 'Faiyum', value: 'Faiyum', stateCode: 'EGFYM'},
    {label: 'Gharbia', value: 'Gharbia', stateCode: 'EGGH'},
    {label: 'Giza', value: 'Giza', stateCode: 'EGGZ'},
    {label: 'Ismailia', value: 'Ismailia', stateCode: 'EGIS'},
    {label: 'South Sinai', value: 'South Sinai', stateCode: 'EGJS'},
    {label: 'Qalyubia', value: 'Qalyubia', stateCode: 'EGKB'},
    {label: 'Kafr el-Sheikh', value: 'Kafr el-Sheikh', stateCode: 'EGKFS'},
    {label: 'Qena', value: 'Qena', stateCode: 'EGKN'},
    {label: 'Luxor', value: 'Luxor', stateCode: 'EGLX'},
    {label: 'Minya', value: 'Minya', stateCode: 'EGMN'},
    {label: 'Monufia', value: 'Monufia', stateCode: 'EGMNF'},
    {label: 'Matrouh', value: 'Matrouh', stateCode: 'EGMT'},
    {label: 'Port Said', value: 'Port Said', stateCode: 'EGPTS'},
    {label: 'Sohag', value: 'Sohag', stateCode: 'EGSHG'},
    {label: 'Al Sharqia', value: 'Al Sharqia', stateCode: 'EGSHR'},
    {label: 'North Sinai', value: 'North Sinai', stateCode: 'EGSIN'},
    {label: 'Suez', value: 'Suez', stateCode: 'EGSUZ'},
    {label: 'New Valley', value: 'New Valley', stateCode: 'EGWAD'},
  ],
  CATEGORIES_DATA: [
    {
      id: 1,
      title: 'Tops',
    },
    {
      id: 2,
      title: 'Blazers',
    },
  ],
  CATEGORIES_SELECTED_DATA: [
    {
      id: 1,
      image: '',
      title: 'T-shirt spanish',
      name: 'Mango',
      discount: '10.00',
      price: '21$',
    },
    {
      id: 2,
      image: '',
      title: 'T-shirt',
      name: 'Perkins',
      discount: '10.00',
      price: '21$',
    },
    {
      id: 3,
      image: '',
      title: 'T-shirt',
      name: 'Perkins 2',
      discount: '10.00',
      price: '21$',
    },
  ],
  PRODUCT_DETAIL: {
    images: [
      {
        id: 2,
        image: '',
      },
      {
        id: 3,
        image: '',
      },
      {
        id: 3,
        image: '',
      },
    ],
    title: 'T-shirt',
    name: 'Perkins 2',
    discount: 10.0,
    price: '21$',
    description: 'Lorem fdsfsdnf fdsfsdf ',
  },
  CART_LIST: [
    {
      id: 1,
      image: '',
      name: 'T-shirt spanish',
      color: 'Mango',
      quantity: 1,
      size: 'L',
      price: '21$',
    },
    {
      id: 2,
      image: '',
      name: 'T-shirt spanish',
      color: 'Mango',
      quantity: 1,
      size: 'M',
      price: '21$',
    },
    // {
    //     id: 3,
    //     image: "",
    //     name: "T-shirt spanish",
    //     color: "Mango",
    //     size: "S",
    //     price: "21$"
    // },
    // {
    //     id: 4,
    //     image: "",
    //     name: "T-shirt spanish",
    //     color: "Mango",
    //     size: "M",
    //     price: "21$"
    // },
    // {
    //     id: 5,
    //     image: "",
    //     name: "T-shirt spanish",
    //     color: "Mango",
    //     size: "S",
    //     price: "21$"
    // }
  ],
  FEED_MENU_ITEMS: [
    {
      id: 1,
      title: 'Notification',
      icon: images.notification,
    },
    {
      id: 2,
      title: 'Telegram',
      icon: images.telegram,
    },
  ],
  FEED_DATA: {
    feeds_page_count: 12,
    page_number: '1',
    results: [
      {
        id: 'l1LVQBj8GEV14Pad4PFM',
        title:
          'How do you have a digital Hair consultation? What are some example of questions you ask? ',
        uid: 'vvDeSiu8Z1gW73pN7xVfB6LiGA52',
        totalContibutions: null,
        upVotes: 2,
        tags: ['booking', 'clients', 'education', 'freelance', 'hairstylist'],
        postTypeTitle: 'Ask the Expert',
        postTypeType: 1,
        isSharedFeed: false,
        isGroupPost: false,
        isDeleted: false,
        link: null,
        featured: true,
        featuredStart: '2020-09-17T23:49:32.000Z',
        expires: '2020-09-23T14:41:32.000Z',
        created: '2020-09-17T23:49:32.000Z',
        comments: 2,
        username: 'Jillian Fisher',
        jobTitle: 'Hairstylist',
        groupId: null,
        inCognito: 1,
        totalViews: 23,
        sharedCurrentFeed: null,
        sharedFeeds: [],
        photos: [],
      },
      {
        id: 'gIoH2LZ74YkYpyThr7Lt',
        title:
          'Hello fellow stylists and students... I’m going over what school fees I have before I graduate and the supplies charge during the closing of school and reopens is ridiculous. We were closed for 2 1/2 months, and when we came back, the director was not placing any color orders, back bar supplies, foiling supplies. We didn’t have 20 volume for 3 weeks and the school was supposed to make do with the limited amount of clients they allowed back in. We don’t take walk in any more, appts are made and screened 24 hrs in advance. Most who book don’t show up. When they do.... looking for styling products around the whole school to blow out and polish clients is a hint. We all have to share 1 of anything on the sales floor.  We have a few let’s of shampoo left but sharing two gallons of cond on floor. We have 3 broken shampoo bowls,  a hole in the ceiling, broken chairs, no lighting .... I can go on and on. And to charge per student a supplies fee in For two quarters of the year of $1309.00 including tax , is RIDICULOUS.  Anyone attending empire beauty, get out and go for an apprenticeship. You’ll learn more and won’t have a huge loan to repay. ',
        uid: 'b1tw0wGHDBaLQnRJ2kgZ3khOFrp2',
        totalContibutions: null,
        upVotes: 5,
        tags: ['business'],
        postTypeTitle: 'Ask the Expert',
        postTypeType: 1,
        isSharedFeed: false,
        isGroupPost: false,
        isDeleted: false,
        link: null,
        featured: true,
        featuredStart: '2020-09-17T19:27:05.000Z',
        expires: '2020-09-22T20:35:01.000Z',
        created: '2020-09-17T19:27:05.000Z',
        comments: 19,
        username: 'Regina oakes',
        jobTitle: 'Colorist',
        groupId: null,
        inCognito: 0,
        totalViews: 125,
        sharedCurrentFeed: null,
        sharedFeeds: [],
        photos: [],
      },
      {
        id: 'lhpkgrZvY5sWgdUssMj3',
        title:
          'Does anyone have access to scruples Blazing ? I keep getting a round about answer since February ',
        uid: 'bQw0OknE2pOaEh0C9hdI5AQpKPk1',
        totalContibutions: null,
        upVotes: 1,
        tags: ['colorist'],
        postTypeTitle: 'Ask the Expert',
        postTypeType: 1,
        isSharedFeed: false,
        isGroupPost: false,
        isDeleted: false,
        link: null,
        featured: false,
        featuredStart: '2020-09-18T15:20:46.000Z',
        expires: '2020-09-18T15:20:46.000Z',
        created: '2020-09-18T15:20:46.000Z',
        comments: 3,
        username: 'maria',
        jobTitle: 'Hairstylist',
        groupId: null,
        inCognito: 0,
        totalViews: 11,
        sharedCurrentFeed: null,
        sharedFeeds: [],
        photos: [],
      },
      {
        id: 'VfIh504s8oz34B6NlX65',
        title:
          'if u have a special event commin up pleasee let me know imm aviavable for any makeup occasion 😎',
        uid: 'SLHng5OTQpOqrylwLNvreAL7kPe2',
        totalContibutions: null,
        upVotes: 1,
        tags: ['clients', 'business', 'booking'],
        postTypeTitle: 'Ask the Expert',
        postTypeType: 1,
        isSharedFeed: false,
        isGroupPost: false,
        isDeleted: false,
        link: null,
        featured: false,
        featuredStart: '2020-09-18T15:14:17.000Z',
        expires: '2020-09-18T15:14:17.000Z',
        created: '2020-09-18T15:14:17.000Z',
        comments: 0,
        username: 'Rosy Cortes',
        jobTitle: 'Make-up Artist',
        groupId: null,
        inCognito: 0,
        totalViews: 2,
        sharedCurrentFeed: null,
        sharedFeeds: [],
        photos: [],
      },
      {
        id: 'QpPOznYULG1YE1uAb34q',
        title:
          'If you need help with a formulation , I will help get your target color , no fee just love seeing color properly done .',
        uid: '2VMLbhlxVOe3IK8KniOotDPyOFw1',
        totalContibutions: null,
        upVotes: 3,
        tags: [
          'colorist',
          'clients',
          'culture',
          'celebrity-artist',
          'brow-expert',
        ],
        postTypeTitle: 'Ask the Expert',
        postTypeType: 1,
        isSharedFeed: false,
        isGroupPost: false,
        isDeleted: false,
        link: null,
        featured: false,
        featuredStart: '2020-09-18T13:39:50.000Z',
        expires: '2020-09-18T13:39:50.000Z',
        created: '2020-09-18T13:39:50.000Z',
        comments: 1,
        username:
          'Mark Colasuonno versed in color correction , color consultation , foiliyage, ballyage, target color and modern hair cutting .colors acheived.all techniques in midterm haircutting and blow drying.',
        jobTitle: 'Colorist',
        groupId: null,
        inCognito: 0,
        totalViews: 7,
        sharedCurrentFeed: null,
        sharedFeeds: [],
        photos: [],
      },
      {
        id: 'l1LVQBj8GEV14Pad4PFM',
        title:
          'How do you have a digital Hair consultation? What are some example of questions you ask? ',
        uid: 'vvDeSiu8Z1gW73pN7xVfB6LiGA52',
        totalContibutions: null,
        upVotes: 2,
        tags: ['booking', 'clients', 'education', 'freelance', 'hairstylist'],
        postTypeTitle: 'Ask the Expert',
        postTypeType: 1,
        isSharedFeed: false,
        isGroupPost: false,
        isDeleted: false,
        link: null,
        featured: true,
        featuredStart: '2020-09-17T23:49:32.000Z',
        expires: '2020-09-23T14:41:32.000Z',
        created: '2020-09-17T23:49:32.000Z',
        comments: 2,
        username: 'Jillian Fisher',
        jobTitle: 'Hairstylist',
        groupId: null,
        inCognito: 1,
        totalViews: 23,
        sharedCurrentFeed: null,
        sharedFeeds: [],
        photos: [],
      },
      {
        id: 'C9dAS8vCBCxHvs3eF1ev',
        title:
          'I graduate cosmetology school in November and would love tips on what the best option is for new stylist right out of school. Commission vs hourly ',
        uid: '0MJS3Lp6deWktPqu9tVzO8NFsEN2',
        totalContibutions: null,
        upVotes: 2,
        tags: ['business', 'clients', 'hairstylist', 'students', 'commission'],
        postTypeTitle: 'Ask the Expert',
        postTypeType: 1,
        isSharedFeed: false,
        isGroupPost: false,
        isDeleted: false,
        link: null,
        featured: false,
        featuredStart: '2020-09-17T23:45:25.000Z',
        expires: '2020-09-17T23:45:25.000Z',
        created: '2020-09-17T23:45:25.000Z',
        comments: 2,
        username: 'Kelli Ott ',
        jobTitle: 'Hairstylist',
        groupId: null,
        inCognito: 1,
        totalViews: 10,
        sharedCurrentFeed: null,
        sharedFeeds: [],
        photos: [],
      },
      {
        id: 'xVEk9A2dst0pZEzbucgp',
        title:
          'Virtual CE class coming up on Oct 2nd from 9-1 bilingual all presentation will be posted in english and presented in Spanish .. contact Marcia Garza 956-451-4896',
        uid: 'DjmtzvhOCUg2C2ElvkMQhYnK9wB3',
        totalContibutions: null,
        upVotes: 1,
        tags: ['education', 'esthetician'],
        postTypeTitle: 'Ask the Expert',
        postTypeType: 1,
        isSharedFeed: false,
        isGroupPost: false,
        isDeleted: false,
        link: null,
        featured: false,
        featuredStart: '2020-09-17T23:06:37.000Z',
        expires: '2020-09-17T23:06:37.000Z',
        created: '2020-09-17T23:06:37.000Z',
        comments: 1,
        username: 'Salvador Flores ',
        jobTitle: 'Educator',
        groupId: null,
        inCognito: 0,
        totalViews: 3,
        sharedCurrentFeed: null,
        sharedFeeds: [],
        photos: [],
      },
      {
        id: 'gIoH2LZ74YkYpyThr7Lt',
        title:
          'Hello fellow stylists and students... I’m going over what school fees I have before I graduate and the supplies charge during the closing of school and reopens is ridiculous. We were closed for 2 1/2 months, and when we came back, the director was not placing any color orders, back bar supplies, foiling supplies. We didn’t have 20 volume for 3 weeks and the school was supposed to make do with the limited amount of clients they allowed back in. We don’t take walk in any more, appts are made and screened 24 hrs in advance. Most who book don’t show up. When they do.... looking for styling products around the whole school to blow out and polish clients is a hint. We all have to share 1 of anything on the sales floor.  We have a few let’s of shampoo left but sharing two gallons of cond on floor. We have 3 broken shampoo bowls,  a hole in the ceiling, broken chairs, no lighting .... I can go on and on. And to charge per student a supplies fee in For two quarters of the year of $1309.00 including tax , is RIDICULOUS.  Anyone attending empire beauty, get out and go for an apprenticeship. You’ll learn more and won’t have a huge loan to repay. ',
        uid: 'b1tw0wGHDBaLQnRJ2kgZ3khOFrp2',
        totalContibutions: null,
        upVotes: 5,
        tags: ['business'],
        postTypeTitle: 'Ask the Expert',
        postTypeType: 1,
        isSharedFeed: false,
        isGroupPost: false,
        isDeleted: false,
        link: null,
        featured: true,
        featuredStart: '2020-09-17T19:27:05.000Z',
        expires: '2020-09-22T20:35:01.000Z',
        created: '2020-09-17T19:27:05.000Z',
        comments: 19,
        username: 'Regina oakes',
        jobTitle: 'Colorist',
        groupId: null,
        inCognito: 0,
        totalViews: 125,
        sharedCurrentFeed: null,
        sharedFeeds: [],
        photos: [],
      },
      {
        id: 'LbDJ2CTem5JfcTH5BXb6',
        title:
          'I live to do highlights with color. I like showing my guests that you don’t have to bleach and tone. I’m a colorist darn it! ❤️ Don’t you want to learn my secrets??? ',
        uid: 'IqlOrOHlV0ZpK4wKGhf555UEVGt2',
        totalContibutions: null,
        upVotes: 4,
        tags: ['colorist', 'business'],
        postTypeTitle: 'Ask the Expert',
        postTypeType: 1,
        isSharedFeed: false,
        isGroupPost: false,
        isDeleted: false,
        link: 'http://coastlineedu.com/val',
        featured: true,
        featuredStart: '2020-09-16T19:57:20.000Z',
        expires: '2020-09-17T14:41:45.000Z',
        created: '2020-09-16T19:57:20.000Z',
        comments: 5,
        username: 'Valerie Frazee',
        jobTitle: 'Owner/stylist',
        groupId: null,
        inCognito: 0,
        totalViews: 50,
        sharedCurrentFeed: null,
        sharedFeeds: [],
        photos: ['b3e7156d-177f-4654-8212-2e7103bf8791.jpg'],
      },
      {
        id: '0CALTqjwkMeXSDaggrUd',
        title:
          'I was cleaning combs this morning and noticed someone was using a new dinglehopper. (This gave me a good laugh so I wanted to share it.',
        uid: 'pLeMWE3IWdXOwmthg0Gv00aWfwI3',
        totalContibutions: null,
        upVotes: 6,
        tags: ['tools', 'culture'],
        postTypeTitle: 'Ask the Expert',
        postTypeType: 1,
        isSharedFeed: false,
        isGroupPost: false,
        isDeleted: false,
        link: null,
        featured: false,
        featuredStart: '2020-09-16T14:13:12.000Z',
        expires: '2020-09-16T14:13:12.000Z',
        created: '2020-09-16T14:13:12.000Z',
        comments: 4,
        username: 'Christopher C.',
        jobTitle: 'Barber',
        groupId: null,
        inCognito: 0,
        totalViews: 39,
        sharedCurrentFeed: null,
        sharedFeeds: [],
        photos: ['b72e3280-3803-48df-b7c9-452d20d4825d.jpg'],
      },
      {
        id: 'yQiQogP63F6FmSjG6JU0',
        title:
          'Another great Tuesday conversation on Instagram. Style Coaching my number one tool.',
        uid: '4y5ntvGNAbWmdTxUAgz84H9t1fx2',
        totalContibutions: null,
        upVotes: 4,
        tags: ['barber', 'business', 'hairstylist', 'students', 'education'],
        postTypeTitle: 'Ask the Expert',
        postTypeType: 1,
        isSharedFeed: false,
        isGroupPost: false,
        isDeleted: false,
        link: 'https://www.instagram.com/tv/CFLbfqSja1-/?igshid=fu2au5bujq7y',
        featured: false,
        featuredStart: '2020-09-16T01:24:43.000Z',
        expires: '2020-09-16T01:24:43.000Z',
        created: '2020-09-16T01:24:43.000Z',
        comments: 0,
        username: 'Angel del Solar',
        jobTitle: 'Educator',
        groupId: null,
        inCognito: 0,
        totalViews: 16,
        sharedCurrentFeed: null,
        sharedFeeds: [],
        photos: [],
      },
    ],
  },
};
