export default WebService = {
  BASE_URL: 'https://riz.shop/wp-json/wc/v3/',
  API_URL: 'https://riz.shop/api/',
  API_URL_STAGE: 'https://75.101.239.148/wp-json/v3/',
  BASE_URL_CART: 'https://riz.shop/wp-json/cocart/v1/',
  BASE_URL_UPDATE_PASSWORD: 'https://riz.shop/wp-json/riz-api/v1/',
  UPDATE_PASSWORD: 'update_user_password/',
  FORGOT_PASSWORD: 'reset_password',
  LOGIN: 'user/generate_auth_cookie/?',
  // CHANGEPASSWORD: 'user/update_user_password/?',
  NONCEURL: 'get_nonce?json=get_nonce&controller=user&method=register',
  REGISTER: 'user/register?',
  PRODUCTCATEGORIES: 'products/categories',
  CATEGORYWISEPRODUCT: 'products?category=',
  API_URL_PAYMOB: 'https://accept.paymobsolutions.com/api/',
  API_KEY:
    'ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2TkRFME56a3NJbTVoYldVaU9pSnBibWwwYVdGc0luMC5mMFZOSHBNZVZUOXpNeFlHR0J6WkVQTEdZeFhLOHpDNnd1emw1TFU2U0xLQ1FYRlJYUmUzMzRvZl9xNElHT2lpamVRYjAwN211UmhTSEJzLTdzQW9qZw==',
  AUTH_TOKEN: 'auth/tokens',
  ORDER_REGISTER: 'ecommerce/orders',
  PAYMENT_KEY: 'acceptance/payment_keys',
  CARD_ID: '102591',
  IFRAME: 'acceptance/iframes/113067?payment_token=',
};
